# Generated by Django 6.0.3 on 2026-04-08 09:42

import random
import string
import core.models
from django.db import migrations, models
from django.db.models import Q


def populate_join_codes(apps, schema_editor):
    Group = apps.get_model("core", "Group")
    alphabet = string.ascii_uppercase + string.digits
    used_codes = set(
        Group.objects.exclude(join_code__isnull=True).exclude(join_code="").values_list("join_code", flat=True)
    )

    for group in Group.objects.filter(Q(join_code__isnull=True) | Q(join_code="")):
        while True:
            candidate = "".join(random.choices(alphabet, k=8))
            if candidate not in used_codes:
                group.join_code = candidate
                group.save(update_fields=["join_code"])
                used_codes.add(candidate)
                break


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="join_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=8,
                null=True,
            ),
        ),
        migrations.RunPython(populate_join_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="group",
            name="join_code",
            field=models.CharField(
                default=core.models.generate_join_code,
                editable=False,
                max_length=8,
                unique=True,
            ),
        ),
    ]
